### PR TITLE
Revamp the UI of the top bar

### PR DESCRIPTION
**Pull request by PeterWarrington**
I have revamped the UI of the top bar to make it more visually appealing as can be seen in the screenshots below. 

I made the following changes:

- Put the logo into centre and removed "Wave in a box" text.
- Put "Online" and "Saved" status indicators underneath the address of the user.
- Put the Language option and the Sign-in button into a jquery UI Settings dialog.
- Removed the border on the top bar.
- Changed the background colour of the main app.

Screenshot

### CODE REVIEW

**Comment by ZMYaro** [comment]
I like the goal of improving the top bar, but I feel like the gear icon should open a menu in the corner, just below the icon.  It would better visually connect the dialog to the action the user just took, and it would be more consistent with well-known apps/sites like Google, Microsoft, Facebook, etc.

Also, does this version still allow for a server title?

**Comment by vega113** [comment]
Great changes in general, however:

We need to try and maximize the vertical screen space to allow more space for the UI.
I would like to retain the red/green color on the status, as the user should be aware when he is working offline. All offline changes will be lost if the wave is closed before saved.

**Comment by PeterWarrington** [comment]
@ZMYaro I have updated the Settings dialog so it appears underneath the settings cog but without the title bar (See picture below). What do you mean by a server title?
@vega113 I changed it so that the colour for the 'Online' indicator is grey as this is the normal status but when it is Offline it still appears Red and Bold (See picture below) 

Screenshot

**Comment by PeterWarrington** [comment]
I have noticed an issue when you first press the cog. The issue is that the dialog displays over the cog, stopping the ability to close it (See screenshot). I will try and solve the issue. I think it's an issue with `position: { at: "left+125px top-50px", of: this }` ~~and that replacing `this` with `$("#SettingsCog")` will solve this issue.~~

Screenshot

**Comment by PeterWarrington** [comment]
Now I think that it's an issue with `$( "#dialog *" ).css("display","unset");` and that calling it before the creation of the dialog will fix it. 
Edit: That doesn't work either, I'll try aligning the "of" attribute to the body
Edit 2: That didn't work either, I'll try aligning the "of" attribute to the "click" event
Edit 3: Now I'm just going to use css for the positioning. It seems to be working.

**Comment by PeterWarrington** [comment]
Doesn't seem to work with IE11.
image
Seems to have not automatically enabled the display of the items in the dialog.
image
Doesn't support 'unset' value. This is probably the issue.
image

**Comment by PeterWarrington** [comment]
Problem with Firefox. Overflow bars shown and Language box too wide.
image

**Comment by PeterWarrington** [comment]
Do you think it is ready to be merged?

**Comment by ZMYaro** [comment]
I just noticed this PR adds jQuery, which was not present before.  Can you not use the dialog framework already present in WIAB?

**Comment by PeterWarrington** [comment]
@ZMYaro Sorry for the delay, I aggree and I will now try to remove JQuery and JQueryUI.

**Comment by PeterWarrington** [comment]
@ZMYaro I have now made the changes.

**Comment by PeterWarrington** [comment]
Do you think it is ready to be merged?

**Comment by vega113** [comment]
Sorry for the delay, I will check the changes and merge.

**Comment by vega113** [comment]
LGTM
Thanks

**Pull request merged**
